name: Grant maintainer edit permission if not already granted

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check-edit-permission:

    runs-on: ubuntu-latest

    if: |
      github.event.pull_request.head.repo.fork == true
      && github.event.pull_request.maintainer_can_modify == false

    steps:
      - name: Update the permission on the pull request
        uses: actions/github-script@v3.1.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          script: |
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              maintainer_can_modify: True
            })
